name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  # run `cargo vendor` and cache it
  vendor_sources:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        name: Update crate cargo-vendor cache
        id: vendor_cache
        with:
          path: |
            .cargo
            vendor
          key: cargo-vendor-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-vendor
          enableCrossOsArchive: true

      - uses: actions/cache@v3
        name: Update cargo registry cache
        if: steps.vendor_cache.outputs.cache-hit != 'true'
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-cache-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-cache

      - name: Vendor sources
        if: steps.vendor_cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p .cargo
          mkdir -p vendor
          cargo vendor --versioned-dirs --locked >.cargo/config.toml

  test_sameold:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        features: ['', 'chrono']

    runs-on: ${{ matrix.os }}

    needs: vendor_sources

    env:
      CARGO_NET_OFFLINE: "true"

    steps:
      - uses: actions/checkout@v3

      - name: Record environment
        shell: bash
        run: cargo version

      - uses: actions/cache/restore@v3
        name: Restore crate cargo-vendor cache
        with:
          path: |
            .cargo
            vendor
          key: cargo-vendor-${{ hashFiles('**/Cargo.lock') }}
          enableCrossOsArchive: true
          fail-on-cache-miss: true

      - name: Build and test sameold
        shell: bash
        run: |
          cargo test --frozen -p sameold --verbose --no-default-features --features "${{ matrix.features }}"

  test_samedec:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    needs: vendor_sources

    env:
      CARGO_NET_OFFLINE: "true"

    steps:
      - uses: actions/checkout@v3

      - name: Record environment
        shell: bash
        run: cargo version

      - uses: actions/cache/restore@v3
        name: Restore crate cargo-vendor cache
        with:
          path: |
            .cargo
            vendor
          key: cargo-vendor-${{ hashFiles('**/Cargo.lock') }}
          enableCrossOsArchive: true
          fail-on-cache-miss: true

      - name: Build and unit-test samedec
        shell: bash
        run: |
          cargo test --frozen -p samedec --verbose

      - name: Run integration tests
        shell: bash
        run: |
          pushd sample
          ./test.sh
          popd